[tasks.help]
script = """
cat<<EOF
Usage:
    cargo make [COMMAND]

Commands:
    run            Build project and run it locally
    build-lambda   Build the Lambda function artifacts.
    build-iac      Build infra as code binary
    deploy         Build and deploy the Lambda function artifacts.
    deploy-beta    Build and deploy the Lambda function to wkw-beta app (need to initialize with wkw-beta first)
    logs           Tail logs


"""

[tasks.build-lambda]
command = "docker"
args = [
  "build",
  "--build-arg=BIN=${CARGO_MAKE_PROJECT_NAME}",
  "--tag=${CARGO_MAKE_PROJECT_NAME}-lambda-artifact-builder",
  "--output=type=local,dest=./lambda-artifact",
  ".",
]
dependencies = ["build"]

[tasks.build-iac]
command = "cargo"
args = ["build", "--bin=iac", "--release"]

[tasks.deploy]
command = "./target/release/iac"
args = ["deploy"]

[tasks.deploy-beta]
command = "./target/release/iac"
args = ["--name=wkw-beta", "deploy"]

dependencies = ["build-iac", "build-lambda"]

[tasks.run]
command = "./target/debug/wkw"
dependencies = ["build"]

[tasks.log]
command = "./target/release/iac"
args = ["log", "tail"]
dependencies = ["build-iac"]
