[tasks.help]
script = """
cat<<EOF
Usage:
    cargo make [COMMAND]

Commands:
    run-locally    Build project and run it locally
    build-lambda   Build the Lambda function artifacts.
    deploy         Build and deploy the Lambda function artifacts.


"""

[tasks.build-lambda]
command = "docker"
args = [
  "build",
  "--build-arg=BIN=${CARGO_MAKE_PROJECT_NAME}",
  "--tag=${CARGO_MAKE_PROJECT_NAME}-lambda-artifact-builder",
  "--output=type=local,dest=./lambda-artifact",
  ".",
]
dependencies = ["build"]

[tasks.build-iac]
command = "cargo"
args = ["build", "--bin=iac", "--release"]

[tasks.deploy]
command = "./target/release/iac"
args = ["deploy"]

dependencies = ["build-iac", "build-lambda"]

[tasks.run]
command = "./target/debug/wkw"

dependencies = ["build"]
